remove footer when keyboard shows
alacolang/kolbeh pull request #142
Opened 2020-12-26 16:03 UTC by soroushmz

- add state showFooter and toggle it when text input on focus 

Picture of 
![Screen Shot 2020-12-26 at 7 31 17 PM](https://user-images.githubusercontent.com/26489138/103155019-2fb35f00-47b1-11eb-9447-3069c4871989.png)

2020-12-26 16:37 UTC, yassermzh requested changes
thanks. checked locally. works fine with hiding the footer. 
but closing the keyboard, it won't show the footer back.

2020-12-26 18:26 UTC, yassermzh commented on packages/app/src/pages/happiness-exercise/add-idea-input.tsx
> +    toggleHideFooterAndDescription();
I think it's better to explicitly set the flag to true to hide, 
and to show, set it to false. toggling usually is not recommended. for some reason, it could get into some unwanted state.

2020-12-26 18:51 UTC, soroushmz commented on packages/app/src/pages/happiness-exercise/add-idea-input.tsx
> +    toggleHideFooterAndDescription();
Agreed, I removed toggling and set it to true/false value instead

2020-12-26 21:25 UTC, yassermzh commented on packages/app/src/pages/happiness-exercise/add-idea-input.tsx
> +const ADD_IDEA_HEIGHT_WHEN_KEYBOARD_SHOWS = 120 * 2;
As we already defined the height in https://github.com/alacolang/kolbeh/blob/1531bfcd0aadefa9f18ff16cc45aee1fcbd819f5/packages/app/src/pages/happiness-exercise/index.tsx#L27
maybe it's better to use that one. (this introduced from previous refactoring, not yours, but as you touching this, maybe you can make it better).

2020-12-26 21:29 UTC, yassermzh commented on packages/app/src/pages/happiness-exercise/add-idea-input.tsx
> +    setIdeaInputHeight(ADD_IDEA_HEIGHT_WHEN_KEYBOARD_SHOWS);
instead of setting the height to 2*120, maybe you can get calculate the height of by: window height - keyboard height - some-fixed-margin-padding.

keyboard height is available in keyboardDidShow as input event: https://stackoverflow.com/a/60682069/1775111.

2020-12-27 09:06 UTC, soroushmz commented on packages/app/src/pages/happiness-exercise/add-idea-input.tsx
> +const ADD_IDEA_HEIGHT_WHEN_KEYBOARD_SHOWS = 120 * 2;
Agreed, I removed the new constants and used the old one

2020-12-27 09:08 UTC, soroushmz commented on packages/app/src/pages/happiness-exercise/add-idea-input.tsx
> +    setIdeaInputHeight(ADD_IDEA_HEIGHT_WHEN_KEYBOARD_SHOWS);
Implemented these ideas and now text input height is not fixed and changes by keyboard height

2020-12-27 09:49 UTC, yassermzh approved these changes
Thanks for addressing all comments. LGTM.

2020-12-27 12:41 UTC, merged